models:
    wiener_blind_noise:
        gauss_blur: True
        motion_blur: True
        eye_blur: True
        RGB: True
        params:
            balance: 1e-2
            clip: True

    usrnet:
        gauss_blur: True
        motion_blur: True
        eye_blur: True
        RGB: True
        model_path: 'models/usrnet.pth'
        params:
            scale_factor: 1
            noise_level: 0
            device: 'cuda'

    dwdn:
        gauss_blur: False
        motion_blur: True
        eye_blur: False
        RGB: True
        model_path: 'models/model_DWDN.pt'
        params:
            n_levels: 2
            scale: 0.5
            device: 'cuda'

    kerunc:
        gauss_blur: False
        motion_blur: True
        eye_blur: False
        RGB: False
        model_path: 'models/keruncnet/noise_0pp'
        params:
            lmds: [0.005, 0.1, 0.1, 0.1, 0.1]
            device: 'cuda'
  
dataset:
    benchmark_list_path: 'datasets/short_dataset.txt'
    blur:
        sigma: 0.01
        mu: 0